language: python
matrix:
  include:
    - python: 3.6
      arch: amd64
      env: TOXENV=py
    - python: 3.5
      arch: amd64
      env: TOXENV=py
    - python: 3.4
      arch: amd64
      env: TOXENV=py
    - python: 2.7
      arch: amd64
      env: TOXENV=py
    - python: 3.6
      arch: ppc64le
      env: TOXENV=py
    - python: 3.5
      arch: ppc64le
      env: TOXENV=py
    - python: 3.4
      arch: ppc64le
      env: TOXENV=py
    - python: 2.7
      arch: ppc64le
      env: TOXENV=py
    - python: pypy
      env: TOXENV=py

sudo: false

before_install:
     - | 
        if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then
            sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels
        fi
install:
    - pip install -U pip
    - pip install -U tox coverage coveralls
script:
    - tox
after_success:
    - coveralls
